// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SIM-MBKM/filestorage/storage"
	"github.com/google/wire"
	"gorm.io/gorm"
	"registration-service/config"
	"registration-service/controller"
	"registration-service/repository"
	"registration-service/service"
)

// Injectors from wire.go:

func InitializeRegistration(db *gorm.DB, secretKey config.SecretKey, userManagementbaseURI config.UserManagementbaseURI, activityManagementbaseURI config.ActivityManagementbaseURI, matchingManagementbaseURI config.MatchingManagementbaseURI, monitoringManagementbaseURI config.MonitoringManagementbaseURI, brokerbaseURI config.BrokerbaseURI, asyncURIs config.AsyncURIs, config2 *storage.Config, tokenManager *storage.CacheTokenManager) (controller.RegistrationController, error) {
	registrationRepository := ProvideRegistrationRepository(db)
	documentRepository := ProvideDocumentRepository(db)
	registrationService := ProvideRegistrationService(registrationRepository, documentRepository, secretKey, userManagementbaseURI, activityManagementbaseURI, matchingManagementbaseURI, monitoringManagementbaseURI, brokerbaseURI, asyncURIs, config2, tokenManager)
	registrationController := ProvideRegistrationController(registrationService)
	return registrationController, nil
}

func InitializeDocument(db *gorm.DB, config2 *storage.Config, tokenManager *storage.CacheTokenManager) (controller.DocumentController, error) {
	documentRepository := ProvideDocumentRepository(db)
	registrationRepository := ProvideRegistrationRepository(db)
	documentService := ProvideDocumentService(documentRepository, registrationRepository, config2, tokenManager)
	documentController := ProvideDocumentController(documentService)
	return documentController, nil
}

// wire.go:

func ProvideRegistrationRepository(db *gorm.DB) repository.RegistrationRepository {
	return repository.NewRegistrationRepository(db)
}

func ProvideDocumentRepository(db *gorm.DB) repository.DocumentRepository {
	return repository.NewDocumentRepository(db)
}

func ProvideRegistrationService(
	registrationRepository repository.RegistrationRepository,
	documentRepository repository.DocumentRepository,
	secretKey config.SecretKey,
	userManagementbaseURI config.UserManagementbaseURI,
	activityManagementbaseURI config.ActivityManagementbaseURI,
	matchingManagementbaseURI config.MatchingManagementbaseURI,
	monitoringManagementbaseURI config.MonitoringManagementbaseURI,
	brokerbaseURI config.BrokerbaseURI,
	asyncURIs config.AsyncURIs, config2 *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.RegistrationService {
	return service.NewRegistrationService(registrationRepository, documentRepository, string(secretKey), string(userManagementbaseURI), string(activityManagementbaseURI), string(matchingManagementbaseURI), string(monitoringManagementbaseURI), string(brokerbaseURI), []string(asyncURIs), config2, tokenManager)
}

func ProvideRegistrationController(registrationService service.RegistrationService) controller.RegistrationController {
	return controller.NewRegistrationController(registrationService)
}

var RegistrationSet = wire.NewSet(
	ProvideRegistrationRepository,
	ProvideDocumentRepository,
	ProvideRegistrationService,
	ProvideRegistrationController,
)

func ProvideDocumentService(
	documentRepository repository.DocumentRepository,
	registrationRepository repository.RegistrationRepository, config2 *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.DocumentService {
	return service.NewDocumentService(documentRepository, registrationRepository, config2, tokenManager)
}

func ProvideDocumentController(documentService service.DocumentService) controller.DocumentController {
	return controller.NewDocumentController(documentService)
}

var DocumentSet = wire.NewSet(
	ProvideDocumentRepository,
	ProvideRegistrationRepository,
	ProvideDocumentService,
	ProvideDocumentController,
)
